version: '3.5'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT:-8080}:8080
    environment:
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - TIKTOK_SESSION_ID=${TIKTOK_SESSION_ID}
      - IMAGEMAGICK_BINARY=${IMAGEMAGICK_BINARY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSEMBLY_AI_API_KEY=${ASSEMBLY_AI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
    env_file:
      - .env
    volumes:
      - ./Backend:/home/app/Backend
    restart: unless-stopped

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.FE.Nuxt
    env_file:
      - .env
    ports:
      - ${FE_NUXT}:3000
